### ISSUE TITLE
Logging panel not working by default

### ISSUE THREAD

**Issue by romabysen** [pallets-eco/flask-debugtoolbar#122]
With the current version of Flask, 0.12.2, the app.logger does not by default propagate to the root logger. This has the effect that no logging messages will be show in the toolbar.
This can easily be fixed with something like:
```python
if app.debug:
    app.logger.propagate = True
```
This should probably be mentioned in the documentation.

**Comment by davidism** [comment]
I can't reproduce this issue. Running the example application in the repo shows the logged message.
