### ISSUE TITLE
Feature Request: ability to have DEBUG_TB_ENABLED=True but some way to exclude arbitrary Flask endpoints

### ISSUE THREAD

**Issue by jerrydboonstra** [pallets-eco/flask-debugtoolbar#159]
I like to have this toolbar turned on in my cloud -based test environments, but I don't want it to appear on, say, a login page.

It would be wonderful to have either a `DEBUG_TB_DENY_PATHS: list[str]` in configuration, or a `@deny_debugtoolbar` route annotation.

**Comment by acbart** [comment]
Yes, this would be a very useful feature. Not sure why there isn't a way to disable this on a per-route basis? I have some routes that don't make sense to have debug bars.

**Comment by davidism** [comment]
Duplicate of #125
