### ISSUE TITLE
ReadTheDocs builds are broken

### ISSUE THREAD

**Issue by jeffwidman** [pallets-eco/flask-debugtoolbar#228]
I noticed the `latest` docs on https://flask-debugtoolbar.readthedocs.io/en/latest/ are actually the `0.11.0` version, when we're actually on `0.14.1`.

Sure enough, the latest builds are breaking: https://readthedocs.org/projects/flask-debugtoolbar/builds/

**Comment by macnewbold** [comment]
The first build that failed seems to be this one from May 24, 2023:
https://github.com/pallets-eco/flask-debugtoolbar/commit/ce02d2da3c37b3212eebafa9392c429b91d13923

However, the error that occurs is `AttributeError: module 'typing' has no attribute 'Literal'` with another message of `sphinx.errors.ConfigError: There is a programmable error in your configuration file:` and the commit doesn't seem to change anything related to it. So I'm wondering if it was some kind of upgrade or version change within ReadTheDocs between Jan 17 and May 24, 2023.

**Comment by jeffwidman** [comment]
Possibly related:
* https://blog.readthedocs.com/migrate-configuration-v2/
* https://github.com/python-zk/kazoo/issues/712
* https://github.com/python-zk/kazoo/pull/710

I'll take a stab at it...
