### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jeffwidman** [pallets-eco/flask-debugtoolbar#244]
Be good to cut a new release now that we've fixed a bunch of deprecation warnings + updated Jquery.

Probably a good idea to first resolve:
* https://github.com/pallets-eco/flask-debugtoolbar/issues/228

I'm planning to look into this this weekend, although we're on vacation visiting extended family so I may not have time, not sure... 😄

**Comment by macnewbold** [comment]
Yes, thanks for the flurry of activity lately. We just got back from a trip, so sorry I was delayed in replying to all of it. I concur that the docs are probably the only thing worth waiting for on the release.

**Comment by rimvydas-zilinskas** [comment]
Is it going to be release on https://pypi.org/project/Flask-DebugToolbar/  ?

**Comment by jeffwidman** [comment]
It's alive! 

https://pypi.org/project/Flask-DebugToolbar/0.15.0/

**Comment by nickjj** [comment]
Thanks Jeff.

In case anyone is wondering, Jeff was involved with merging and keeping tabs on ~20 PRs over the last couple of days prepping this release. Huge shout out to him.
