### ISSUE TITLE
Fix more `JQMIGRATE` notices from our `jquery` upgrade migration

### ISSUE THREAD

**Issue by macnewbold** [pallets-eco/flask-debugtoolbar#281]
Currently 0.15.1 is throwing some JavaScript warnings from `jquery-migrate.js` that we should clean up. This probably isn't a complete list, but ones that I've run into so far include:

- jQuery.trim is deprecated; use String.prototype.trim (from toolbar.js line 2 in `$.cookie`)
- jQuery.fn.unbind() is deprecated (from toolbar.js line 146 in `hide_toolbar()` at `$(document).unbind('keydown.flDebug');`)

There are also two that are issues within `jquery.tablesorter.js` so we may want to update to a newer version of that:
- jQuery.isFunction() is deprecated (line 1029 in `buildCache`)
- jQuery.fn.bind() is deprecated (line 484 in `bindEvents`)

Environment:
- Flask-DebugToolbar version: 0.15.1

**Comment by garinm90** [comment]
Hey, you have any requirements on contributing or can I just clone the repo and issue a PR?
If so, I'll look into updating any deprecated functions.
