### ISSUE TITLE
Include the version number within the library

### ISSUE THREAD

**Issue by lipis** [pallets-eco/flask-debugtoolbar#57]
It would be nice to know which version of the toolbar is currently installed, exactly as in Flask..

Just include the `__version__ = '0.8.0'` in the `__init__.py` for the stable releases and use something like `__version__ = '0.9.0-dev'`for the master branch!

It would be also good idea to include that number inside the VersionDebugPanel so you will know which version of the toolbar is currently running.

**Comment by jeffwidman** [comment]
Pull requests welcome

**Comment by jeffwidman** [comment]
Having looked at this deeper, I would prefer to access the version using `pkg_resources.get_distribution('Flask-DebugToolbar').version`. I would prefer to avoid adding a `__version__` inside of `__init__.py` as so far I haven't seen a compelling reason to add the additional complexity. 

It does seem like a good idea to expose in the UI which version of the toolbar is currently running.

**Comment by lipis** [comment]
it won't work on Google App Engine.. can't find right now another library that went this way and then switched back to the hardcoded version.. :/

**Comment by jeffwidman** [comment]
What won't work inside of Google App Engine? 

Accessing `pkg_resources` or not having a `__version__` inside of `init.py`?

Are there GAE docs explaining this?

**Comment by davidism** [comment]
Use `importlib.metadata.version("package-name") to get the version in a standard way for any installed package.
